// customer/app/pages/orders/index.vue
<template>
  <div>
    <h1 class="text-2xl font-bold text-gray-800 mb-6">My Orders</h1>

    <div v-if="!authStore.isLoggedIn" class="text-center py-16 bg-white rounded-2xl shadow-sm">
      <div class="text-5xl mb-4">🔒</div>
      <p class="text-gray-500 mb-4">Please login to view your orders</p>
      <NuxtLink to="/auth/login"
        class="inline-block bg-blue-600 text-white px-6 py-3 rounded-xl hover:bg-blue-700 transition-colors">
        Login
      </NuxtLink>
    </div>

    <div v-else-if="loading" class="text-center py-16 text-gray-400">
      Loading your orders...
    </div>

    <div v-else-if="orders.length === 0" class="text-center py-16 bg-white rounded-2xl shadow-sm">
      <div class="text-5xl mb-4">📦</div>
      <p class="text-gray-500 mb-2">No orders yet</p>
      <p class="text-gray-400 text-sm mb-6">Your orders will appear here once you place one</p>
      <NuxtLink to="/products"
        class="inline-block bg-blue-600 text-white px-6 py-3 rounded-xl hover:bg-blue-700 transition-colors">
        Start Shopping
      </NuxtLink>
    </div>

    <div v-else class="space-y-4">
      <div v-for="order in orders" :key="order.id"
        class="bg-white rounded-xl shadow-sm overflow-hidden">
        <!-- Header -->
        <div class="flex flex-wrap items-center justify-between px-6 py-4 bg-gray-50 border-b border-gray-100 gap-3">
          <div>
            <p class="font-bold text-gray-800">Order #{{ order.id }}</p>
            <p class="text-xs text-gray-500 mt-0.5">{{ formatDate(order.created_at) }}</p>
          </div>
          <div class="flex items-center gap-4">
            <span :class="`px-3 py-1 rounded-full text-xs font-semibold ${getStatusColor(order.status)}`">
              {{ order.status.toUpperCase() }}
            </span>
            <p class="font-bold text-gray-800 text-lg">{{ formatCurrency(order.final_amount) }}</p>
          </div>
        </div>

        <!-- Body -->
        <div class="px-6 py-4 grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <p class="text-xs text-gray-400 mb-1">Payment Method</p>
            <p class="text-sm font-semibold text-gray-800 uppercase">{{ order.payment_method }}</p>
          </div>
          <div>
            <p class="text-xs text-gray-400 mb-1">Payment Status</p>
            <p class="text-sm font-semibold text-gray-800 capitalize">{{ order.payment_status }}</p>
          </div>
          <div>
            <p class="text-xs text-gray-400 mb-1">Deliver To</p>
            <p class="text-sm font-semibold text-gray-800">{{ order.shipping_name }}</p>
            <p class="text-xs text-gray-500">{{ order.shipping_city }}, {{ order.shipping_state }}</p>
          </div>
          <div>
            <p class="text-xs text-gray-400 mb-1">Shipping</p>
            <p class="text-sm font-semibold"
              :class="order.shipping_amount == 0 ? 'text-green-600' : 'text-gray-800'">
              {{ order.shipping_amount == 0 ? '🎉 FREE' : formatCurrency(order.shipping_amount) }}
            </p>
          </div>
        </div>

        <!-- Cancel -->
        <div v-if="order.status === 'pending'" class="px-6 pb-4">
          <button @click="cancelOrder(order.id)"
            class="text-sm text-red-500 hover:text-red-700 font-medium border border-red-200 px-4 py-1.5 rounded-lg hover:bg-red-50 transition-colors">
            ✕ Cancel Order
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { formatCurrency, formatDate, getStatusColor } from '../../utils/helpers'
import api from '../../utils/api'

const authStore = useAuthStore()
const orders    = ref([])
const loading   = ref(true)

onMounted(async () => {
  if (!authStore.isLoggedIn) { loading.value = false; return }
  try {
    const res = await api.get('/orders')
    orders.value = res.data.data
  } finally {
    loading.value = false
  }
})

const cancelOrder = async (id) => {
  if (!confirm('Cancel this order?')) return
  try {
    await api.put(`/orders/${id}/cancel`)
    const res = await api.get('/orders')
    orders.value = res.data.data
  } catch (err) {
    alert(err.response?.data?.message || 'Failed to cancel')
  }
}
</script>

// admin/src/pages/orders/Orders.jsx
import { useState, useEffect } from 'react'
import orderService from '../../services/orderService'
import { formatCurrency, formatDate, getStatusColor } from '../../utils/helpers'

export default function Orders() {
  const [orders, setOrders]   = useState([])
  const [loading, setLoading] = useState(false)
  const [success, setSuccess] = useState('')

  useEffect(() => { fetchOrders() }, [])

  const fetchOrders = async () => {
    setLoading(true)
    try {
      const res = await orderService.getAll()
      setOrders(res.data.data)
    } finally {
      setLoading(false)
    }
  }

  const handleStatus = async (id, status) => {
    try {
      await orderService.updateStatus(id, status)
      setSuccess('Order status updated!')
      fetchOrders()
      setTimeout(() => setSuccess(''), 3000)
    } catch {}
  }

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-slate-800">Orders</h2>
        <span className="text-sm text-slate-500">{orders.length} total orders</span>
      </div>

      {success && (
        <div className="bg-green-50 text-green-700 border border-green-200 rounded-lg px-4 py-3 mb-4 text-sm">
          {success}
        </div>
      )}

      <div className="bg-white rounded-xl shadow-sm overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="bg-slate-50">
              <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Order ID</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Customer</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Amount</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Payment</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Status</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Date</th>
              <th className="px-6 py-3 text-left text-xs font-semibold text-slate-500 uppercase">Update</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={7} className="text-center py-8 text-slate-400">Loading...</td></tr>
            ) : orders.map(order => (
              <tr key={order.id} className="border-t border-slate-100 hover:bg-slate-50">
                <td className="px-6 py-4 text-sm font-medium text-slate-800">#{order.id}</td>
                <td className="px-6 py-4 text-sm text-slate-600">{order.customer_name}</td>
                <td className="px-6 py-4 text-sm font-medium text-slate-800">
                  {formatCurrency(order.final_amount)}
                </td>
                <td className="px-6 py-4">
                  <span className="px-2 py-1 bg-slate-100 text-slate-600 rounded text-xs uppercase">
                    {order.payment_method}
                  </span>
                </td>
                <td className="px-6 py-4">
                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(order.status)}`}>
                    {order.status}
                  </span>
                </td>
                <td className="px-6 py-4 text-sm text-slate-500">{formatDate(order.created_at)}</td>
                <td className="px-6 py-4">
                  <select
                    value={order.status}
                    onChange={e => handleStatus(order.id, e.target.value)}
                    className="text-xs border border-slate-300 rounded-lg px-2 py-1 focus:outline-none focus:border-blue-500"
                  >
                    <option value="pending">Pending</option>
                    <option value="processing">Processing</option>
                    <option value="shipped">Shipped</option>
                    <option value="delivered">Delivered</option>
                    <option value="cancelled">Cancelled</option>
                  </select>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
